name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            name: ubuntu_latest_Python_3_8
            continue-on-error: true
          - os: ubuntu-latest
            python-version: 3.9
            name: ubuntu_latest_Python_3_9
            continue-on-error: true
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format

    
